name: Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Step 1: Login to Azure
    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: false
        environment: azurecloud
        allow-no-subscriptions: false
        auth-type: SERVICE_PRINCIPAL

    # Step 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Azure Container Registry (ACR)
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: dfacrapp.azurecr.io  # Your ACR Name
        username: ${{ secrets.AZURE_USERNAME }}  # GitHub Secret for ACR username
        password: ${{ secrets.AZURE_PASSWORD }}  # GitHub Secret for ACR password

    # Step 4: Build and Push Docker Image
    - name: Build and Push Docker Image
      run: |
        docker build -t dfacrapp.azurecr.io/my-react-app:v1 .  # Your Docker Image
        docker push dfacrapp.azurecr.io/my-react-app:v1  # Push Docker Image to ACR

    # Step 5: Deploy to Azure App Service
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: dfwebapp  # Your Azure App Service Name
        slot-name: production
        images: dfacrapp.azurecr.io/my-react-app:v1  # Your Docker Image
